[package]
name = "rust-template"
version = "0.0.1"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.39.0", features = ["bitflags"] }
serde_json = "1.0.117"
component = "0.1.1"
klave = "0.2.0"
musig2 = "0.2.4"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:rust-template"

[profile.release]
lto = true
# Tell `rustc` to optimize for small code size.
opt-level = "s"
strip = true
